# Sells for Via Uno

First we import the necessary librarys

In [1]:
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', None)  # Para mostrar todas las filas
pd.set_option('display.max_columns', None)  # Para mostrar todas las columnas
pd.set_option('display.width', None)  # Para que no haya corte de texto
pd.set_option('display.max_colwidth', None)  # Para que no haya corte en el contenido de las celdas

# Extract of data

We import the necesary datas

In [2]:
principal = pd.read_excel('/home/sebastian/Documents/Portfolio/Ventas via uno/costo venta ene 2025.xlsx', skiprows=5)
cost= pd.read_html('/home/sebastian/Documents/Portfolio/Ventas via uno/Costos.xls')[0]
year= pd.read_excel('/home/sebastian/Documents/Portfolio/Ventas via uno/BASE VENTA 2024 2025.xlsx',skiprows=11)

In [3]:
# This is for checking that the data is correct in the final dataframe
num_principal = len(principal)
num_cost = len(cost)
num_year= len(year)
print(num_principal)
print(num_cost)
print(num_year)

3132
8025
19529

# Data cleaning

#### First clean data of cost

In [4]:
cost.head(5)

                 SKU                  Variante  Costo Neto
0  ="22231604002005"  Sandalia Azul Via Uno 35       10969
1  ="22231604002006"  Sandalia Azul Via Uno 36       10969
2  ="22231604002007"  Sandalia Azul Via Uno 37       10969
3  ="22231604002008"  Sandalia Azul Via Uno 38       10969
4  ="22231604002009"  Sandalia Azul Via Uno 39       10969

In [5]:
cost.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8025 entries, 0 to 8024
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SKU         8025 non-null   object
 1   Variante    8025 non-null   object
 2   Costo Neto  8025 non-null   int64
dtypes: int64(1), object(2)
memory usage: 188.2+ KB

In [6]:
cost['SKU']=cost['SKU'].str.replace('"', '', regex=False)
cost['SKU']=cost['SKU'].str.replace("=", '', regex=False)
cost.head()

              SKU                  Variante  Costo Neto
0  22231604002005  Sandalia Azul Via Uno 35       10969
1  22231604002006  Sandalia Azul Via Uno 36       10969
2  22231604002007  Sandalia Azul Via Uno 37       10969
3  22231604002008  Sandalia Azul Via Uno 38       10969
4  22231604002009  Sandalia Azul Via Uno 39       10969

Create an diccionary with relation between SKU and Costo Neto

In [7]:
#Create a dictionary with the cost of each SKU
cost_dict = dict(zip(cost['SKU'], cost['Costo Neto']))
cost_dict

#Count per SKU
count = cost.groupby('SKU').size().reset_index(name='Cantidad')
count_dict = count.set_index('SKU')['Cantidad'].to_dict()
count_dict

{'002': 1,
 '003': 1,
 '004': 1,
 '005': 1,
 '12201502003005': 1,
 '12201502003006': 1,
 '12201502003007': 1,
 '12201502003008': 1,
 '12201502003009': 1,
 '12201502003010': 1,
 '12201502015005': 1,
 '12201502015006': 1,
 '12201502015007': 1,
 '12201502015008': 1,
 '12201502015009': 1,
 '12201502015010': 1,
 '12201503014005': 1,
 '12201503014006': 1,
 '12201503014007': 1,
 '12201503014008': 1,
 '12201503014009': 1,
 '12201503014010': 1,
 '12201503015005': 1,
 '12201503015006': 1,
 '12201503015007': 1,
 '12201503015008': 1,
 '12201503015009': 1,
 '12201503015010': 1,
 '12201504006005': 1,
 '12201504006006': 1,
 '12201504006007': 1,
 '12201504006008': 1,
 '12201504006009': 1,
 '12201504006010': 1,
 '12201504015005': 1,
 '12201504015006': 1,
 '12201504015007': 1,
 '12201504015008': 1,
 '12201504015009': 1,
 '12201504015010': 1,
 '12201505015005': 1,
 '12201505015006': 1,
 '12201505015007': 1,
 '12201505015008': 1,
 '12201505015009': 1,
 '12201505015010': 1,
 '12201505017005': 1,
 '12201505017006': 1,
 '12201505017007': 1,
 '12201505017008': 1,
 '12201505017009': 1,
 '12201505017010': 1,
 '12201505022005': 1,
 '12201505022006': 1,
 '12201505022007': 1,
 '12201505022008': 1,
 '12201505022009': 1,
 '12201505022010': 1,
 '12201506005005': 1,
 '12201506005006': 1,
 '12201506005007': 1,
 '12201506005008': 1,
 '12201506005009': 1,
 '12201506005010': 1,
 '12201506009005': 1,
 '12201506009006': 1,
 '12201506009007': 1,
 '12201506009008': 1,
 '12201506009009': 1,
 '12201506009010': 1,
 '12201506015005': 1,
 '12201506015006': 1,
 '12201506015007': 1,
 '12201506015008': 1,
 '12201506015009': 1,
 '12201506015010': 1,
 '12201507009005': 1,
 '12201507009006': 1,
 '12201507009007': 1,
 '12201507009008': 1,
 '12201507009009': 1,
 '12201507009010': 1,
 '12201507015005': 1,
 '12201507015006': 1,
 '12201507015007': 1,
 '12201507015008': 1,
 '12201507015009': 1,
 '12201507015010': 1,
 '12201508009005': 1,
 '12201508009006': 1,
 '12201508009007': 1,
 '12201508009008': 1,
 '12201508009009': 1,
 '12201508009010': 1,
 '12201508015005': 1,
 '12201508015006': 1,
 '12201508015007': 1,
 '12201508015008': 1,
 '12201508015009': 1,
 '12201508015010': 1,
 '12201508022005': 1,
 '12201508022006': 1,
 '12201508022007': 1,
 '12201508022008': 1,
 '12201508022009': 1,
 '12201508022010': 1,
 '12201509014005': 1,
 '12201509014006': 1,
 '12201509014007': 1,
 '12201509014008': 1,
 '12201509014009': 1,
 '12201509014010': 1,
 '12201509025005': 1,
 '12201509025006': 1,
 '12201509025007': 1,
 '12201509025008': 1,
 '12201509025009': 1,
 '12201509025010': 1,
 '12201510014005': 1,
 '12201510014006': 1,
 '12201510014007': 1,
 '12201510014008': 1,
 '12201510014009': 1,
 '12201510014010': 1,
 '12201510015005': 1,
 '12201510015006': 1,
 '12201510015007': 1,
 '12201510015008': 1,
 '12201510015009': 1,
 '12201510015010': 1,
 '12201511014005': 1,
 '12201511014006': 1,
 '12201511014007': 1,
 '12201511014008': 1,
 '12201511014009': 1,
 '12201511014010': 1,
 '12201511028005': 1,
 '12201511028006': 1,
 '12201511028007': 1,
 '12201511028008': 1,
 '12201511028009': 1,
 '12201511028010': 1,
 '12201512015005': 1,
 '12201512015006': 1,
 '12201512015007': 1,
 '12201512015008': 1,
 '12201512015009': 1,
 '12201512015010': 1,
 '12201512020005': 1,
 '12201512020006': 1,
 '12201512020007': 1,
 '12201512020008': 1,
 '12201512020009': 1,
 '12201512020010': 1,
 '12201701004005': 1,
 '12201701004006': 1,
 '12201701004007': 1,
 '12201701004008': 1,
 '12201701004009': 1,
 '12201701004010': 1,
 '12201701014005': 1,
 '12201701014006': 1,
 '12201701014007': 1,
 '12201701014008': 1,
 '12201701014009': 1,
 '12201701014010': 1,
 '12212301003005': 1,
 '12212301003006': 1,
 '12212301003007': 1,
 '12212301003008': 1,
 '12212301003009': 1,
 '12212301003010': 1,
 '12212301015005': 1,
 '12212301015006': 1,
 '12212301015007': 1,
 '12212301015008': 1,
 '12212301015009': 1,
 '12212301015010': 1,
 '12212302015005': 1,
 '12212302015006': 1,
 '12212302015007': 1,
 '12212302015008': 1,
 '12212302015009': 1,
 '12212302015010': 1,
 '12212303023005': 1,
 '12212303023006': 1,
 '12212303023007': 1,
 '12212303023008': 1,
 '12212303023009': 1,
 '12212303023010': 1,
 '12212401015005': 1,
 '12212401015006': 1,
 '12212401015007': 1,
 '12212401015008': 1,
 '12212401015009': 1,
 '12212401015010': 1,
 '12212402009005': 1,
 '12212402009006': 1,
 '12212402009007': 1,
 '12212402009008': 1,
 '12212402009009': 1,
 '12212402009010': 1,
 '12212402015005': 1,
 '12212402015006': 1,
 '12212402015007': 1,
 '12212402015008': 1,
 '12212402015009': 1,
 '12212402015010': 1,
 '12212402029005': 1,
 '12212402029006': 1,
 '12212402029007': 1,
 '12212402029008': 1,
 '12212402029009': 1,
 '12212402029010': 1,
 '12212405015005': 1,
 '12212405015006': 1,
 '12212405015007': 1,
 '12212405015008': 1,
 '12212405015009': 1,
 '12212405015010': 1,
 '12212405023005': 1,
 '12212405023006': 1,
 '12212405023007': 1,
 '12212405023008': 1,
 '12212405023009': 1,
 '12212405023010': 1,
 '12213401015005': 1,
 '12213401015006': 1,
 '12213401015007': 1,
 '12213401015008': 1,
 '12213401015009': 1,
 '12213401015010': 1,
 '12222501015005': 1,
 '12222501015006': 1,
 '12222501015007': 1,
 '12222501015008': 1,
 '12222501015009': 1,
 '12222501015010': 1,
 '12222501031005': 1,
 '12222501031006': 1,
 '12222501031007': 1,
 '12222501031008': 1,
 '12222501031009': 1,
 '12222501031010': 1,
 '12223401015005': 1,
 '12223401015006': 1,
 '12223401015007': 1,
 '12223401015008': 1,
 '12223401015009': 1,
 '12223401015010': 1,
 '12223402015005': 1,
 '12223402015006': 1,
 '12223402015007': 1,
 '12223402015008': 1,
 '12223402015009': 1,
 '12223402015010': 1,
 '12223403015005': 1,
 '12223403015006': 1,
 '12223403015007': 1,
 '12223403015008': 1,
 '12223403015009': 1,
 '12223403015010': 1,
 '12223502009005': 1,
 '12223502009006': 1,
 '12223502009007': 1,
 '12223502009008': 1,
 '12223502009009': 1,
 '12223502009010': 1,
 '12223502015005': 1,
 '12223502015006': 1,
 '12223502015007': 1,
 '12223502015008': 1,
 '12223502015009': 1,
 '12223502015010': 1,
 '12223503003005': 1,
 '12223503003006': 1,
 '12223503003007': 1,
 '12223503003008': 1,
 '12223503003009': 1,
 '12223503003010': 1,
 '12223503015005': 1,
 '12223503015006': 1,
 '12223503015007': 1,
 '12223503015008': 1,
 '12223503015009': 1,
 '12223503015010': 1,
 '12223504004005': 1,
 '12223504004006': 1,
 '12223504004007': 1,
 '12223504004008': 1,
 '12223504004009': 1,
 '12223504004010': 1,
 '12223504014005': 1,
 '12223504014006': 1,
 '12223504014007': 1,
 '12223504014008': 1,
 '12223504014009': 1,
 '12223504014010': 1,
 '12223504015005': 1,
 '12223504015006': 1,
 '12223504015007': 1,
 '12223504015008': 1,
 '12223504015009': 1,
 '12223504015010': 1,
 '12223505015005': 1,
 '12223505015006': 1,
 '12223505015007': 1,
 '12223505015008': 1,
 '12223505015009': 1,
 '12223505015010': 1,
 '12223505029005': 1,
 '12223505029006': 1,
 '12223505029007': 1,
 '12223505029008': 1,
 '12223505029009': 1,
 '12223505029010': 1,
 '12223506003005': 1,
 '12223506003006': 1,
 '12223506003007': 1,
 '12223506003008': 1,
 '12223506003009': 1,
 '12223506003010': 1,
 '12223506015005': 1,
 '12223506015006': 1,
 '12223506015007': 1,
 '12223506015008': 1,
 '12223506015009': 1,
 '12223506015010': 1,
 '12223506031005': 1,
 '12223506031006': 1,
 '12223506031007': 1,
 '12223506031008': 1,
 '12223506031009': 1,
 '12223506031010': 1,
 '12223507023005': 1,
 '12223507023006': 1,
 '12223507023007': 1,
 '12223507023008': 1,
 '12223507023009': 1,
 '12223507023010': 1,
 '12223507034005': 1,
 '12223507034006': 1,
 '12223507034007': 1,
 '12223507034008': 1,
 '12223507034009': 1,
 '12223507034010': 1,
 '12231301015005': 1,
 '12231301015006': 1,
 '12231301015007': 1,
 '12231301015008': 1,
 '12231301015009': 1,
 '12231301015010': 1,
 '12231301023005': 1,
 '12231301023006': 1,
 '12231301023007': 1,
 '12231301023008': 1,
 '12231301023009': 1,
 '12231301023010': 1,
 '12231302015005': 1,
 '12231302015006': 1,
 '12231302015007': 1,
 '12231302015008': 1,
 '12231302015009': 1,
 '12231302015010': 1,
 '12231302023005': 1,
 '12231302023006': 1,
 '12231302023007': 1,
 '12231302023008': 1,
 '12231302023009': 1,
 '12231302023010': 1,
 '12231303015005': 1,
 '12231303015006': 1,
 '12231303015007': 1,
 '12231303015008': 1,
 '12231303015009': 1,
 '12231303015010': 1,
 '12231303023005': 1,
 '12231303023006': 1,
 '12231303023007': 1,
 '12231303023008': 1,
 '12231303023009': 1,
 '12231303023010': 1,
 '12231304015005': 1,
 '12231304015006': 1,
 '12231304015007': 1,
 '12231304015008': 1,
 '12231304015009': 1,
 '12231304015010': 1,
 '12231305015005': 1,
 '12231305015006': 1,
 '12231305015007': 1,
 '12231305015008': 1,
 '12231305015009': 1,
 '12231305015010': 1,
 '12231305023005': 1,
 '12231305023006': 1,
 '12231305023007': 1,
 '12231305023008': 1,
 '12231305023009': 1,
 '12231305023010': 1,
 '12231306015005': 1,
 '12231306015006': 1,
 '12231306015007': 1,
 '12231306015008': 1,
 '12231306015009': 1,
 '12231306015010': 1,
 '12231306023005': 1,
 '12231306023006': 1,
 '12231306023007': 1,
 '12231306023008': 1,
 '12231306023009': 1,
 '12231306023010': 1,
 '12231307015005': 1,
 '12231307015006': 1,
 '12231307015007': 1,
 '12231307015008': 1,
 '12231307015009': 1,
 '12231307015010': 1,
 '12231308015005': 1,
 '12231308015006': 1,
 '12231308015007': 1,
 '12231308015008': 1,
 '12231308015009': 1,
 '12231308015010': 1,
 '12231309015005': 1,
 '12231309015006': 1,
 '12231309015007': 1,
 '12231309015008': 1,
 '12231309015009': 1,
 '12231309015010': 1,
 '12231310015005': 1,
 '12231310015006': 1,
 '12231310015007': 1,
 '12231310015008': 1,
 '12231310015009': 1,
 '12231310015010': 1,
 '12231311022005': 1,
 '12231311022006': 1,
 '12231311022007': 1,
 '12231311022008': 1,
 '12231311022009': 1,
 '12231311022010': 1,
 '12231311023005': 1,
 '12231311023006': 1,
 '12231311023007': 1,
 '12231311023008': 1,
 '12231311023009': 1,
 '12231311023010': 1,
 '12231312003005': 1,
 '12231312003006': 1,
 '12231312003007': 1,
 '12231312003008': 1,
 '12231312003009': 1,
 '12231312003010': 1,
 '12231312015005': 1,
 '12231312015006': 1,
 '12231312015007': 1,
 '12231312015008': 1,
 '12231312015009': 1,
 '12231312015010': 1,
 '12231314015005': 1,
 '12231314015006': 1,
 '12231314015007': 1,
 '12231314015008': 1,
 '12231314015009': 1,
 '12231314015010': 1,
 '12231314023005': 1,
 '12231314023006': 1,
 '12231314023007': 1,
 '12231314023008': 1,
 '12231314023009': 1,
 '12231314023010': 1,
 '12231315015005': 1,
 '12231315015006': 1,
 '12231315015007': 1,
 '12231315015008': 1,
 '12231315015009': 1,
 '12231315015010': 1,
 '12231315023005': 1,
 '12231315023006': 1,
 '12231315023007': 1,
 '12231315023008': 1,
 '12231315023009': 1,
 '12231315023010': 1,
 '12231401015005': 1,
 '12231401015006': 1,
 '12231401015007': 1,
 '12231401015008': 1,
 '12231401015009': 1,
 '12231401015010': 1,
 '12231402015005': 1,
 '12231402015006': 1,
 '12231402015007': 1,
 '12231402015008': 1,
 '12231402015009': 1,
 '12231402015010': 1,
 '12231402023005': 1,
 '12231402023006': 1,
 '12231402023007': 1,
 '12231402023008': 1,
 '12231402023009': 1,
 '12231402023010': 1,
 '12231403015005': 1,
 '12231403015006': 1,
 '12231403015007': 1,
 '12231403015008': 1,
 '12231403015009': 1,
 '12231403015010': 1,
 '12231403023005': 1,
 '12231403023006': 1,
 '12231403023007': 1,
 '12231403023008': 1,
 '12231403023009': 1,
 '12231403023010': 1,
 '12231404015005': 1,
 '12231404015006': 1,
 '12231404015007': 1,
 '12231404015008': 1,
 '12231404015009': 1,
 '12231404015010': 1,
 '12231404023005': 1,
 '12231404023006': 1,
 '12231404023007': 1,
 '12231404023008': 1,
 '12231404023009': 1,
 '12231404023010': 1,
 '12231405005005': 1,
 '12231405005006': 1,
 '12231405005007': 1,
 '12231405005008': 1,
 '12231405005009': 1,
 '12231405005010': 1,
 '12231405023005': 1,
 '12231405023006': 1,
 '12231405023007': 1,
 '12231405023008': 1,
 '12231405023009': 1,
 '12231405023010': 1,
 '12231406015005': 1,
 '12231406015006': 1,
 '12231406015007': 1,
 '12231406015008': 1,
 '12231406015009': 1,
 '12231406015010': 1,
 '12231406023005': 1,
 '12231406023006': 1,
 '12231406023007': 1,
 '12231406023008': 1,
 '12231406023009': 1,
 '12231406023010': 1,
 '12231407015005': 1,
 '12231407015006': 1,
 '12231407015007': 1,
 '12231407015008': 1,
 '12231407015009': 1,
 '12231407015010': 1,
 '12231407023005': 1,
 '12231407023006': 1,
 '12231407023007': 1,
 '12231407023008': 1,
 '12231407023009': 1,
 '12231407023010': 1,
 '12231407024005': 1,
 '12231407024006': 1,
 '12231407024007': 1,
 '12231407024008': 1,
 '12231407024009': 1,
 '12231407024010': 1,
 '12231408015005': 1,
 '12231408015006': 1,
 '12231408015007': 1,
 '12231408015008': 1,
 '12231408015009': 1,
 '12231408015010': 1,
 '12231409015005': 1,
 '12231409015006': 1,
 '12231409015007': 1,
 '12231409015008': 1,
 '12231409015009': 1,
 '12231409015010': 1,
 '12231409023005': 1,
 '12231409023006': 1,
 '12231409023007': 1,
 '12231409023008': 1,
 '12231409023009': 1,
 '12231409023010': 1,
 '12231410015005': 1,
 '12231410015006': 1,
 '12231410015007': 1,
 '12231410015008': 1,
 '12231410015009': 1,
 '12231410015010': 1,
 '12231410023005': 1,
 '12231410023006': 1,
 '12231410023007': 1,
 '12231410023008': 1,
 '12231410023009': 1,
 '12231410023010': 1,
 '12231411003005': 1,
 '12231411003006': 1,
 '12231411003007': 1,
 '12231411003008': 1,
 '12231411003009': 1,
 '12231411003010': 1,
 '12231411004005': 1,
 '12231411004006': 1,
 '12231411004007': 1,
 '12231411004008': 1,
 '12231411004009': 1,
 '12231411004010': 1,
 '12231411015005': 1,
 '12231411015006': 1,
 '12231411015007': 1,
 '12231411015008': 1,
 '12231411015009': 1,
 '12231411015010': 1,
 '12231412015005': 1,
 '12231412015006': 1,
 '12231412015007': 1,
 '12231412015008': 1,
 '12231412015009': 1,
 '12231412015010': 1,
 '12231416015005': 1,
 '12231416015006': 1,
 '12231416015007': 1,
 '12231416015008': 1,
 '12231416015009': 1,
 '12231416015010': 1,
 '12231416024005': 1,
 '12231416024006': 1,
 '12231416024007': 1,
 '12231416024008': 1,
 '12231416024009': 1,
 '12231416024010': 1,
 '12231417005005': 1,
 '12231417005006': 1,
 '12231417005007': 1,
 '12231417005008': 1,
 '12231417005009': 1,
 '12231417005010': 1,
 '12231417015005': 1,
 '12231417015006': 1,
 '12231417015007': 1,
 '12231417015008': 1,
 '12231417015009': 1,
 '12231417015010': 1,
 '12232301015005': 1,
 '12232301015006': 1,
 '12232301015007': 1,
 '12232301015008': 1,
 '12232301015009': 1,
 '12232301015010': 1,
 '12232302015005': 1,
 '12232302015006': 1,
 '12232302015007': 1,
 '12232302015008': 1,
 '12232302015009': 1,
 '12232302015010': 1,
 '12232303014005': 1,
 '12232303014006': 1,
 '12232303014007': 1,
 '12232303014008': 1,
 '12232303014009': 1,
 '12232303014010': 1,
 '12232306015005': 1,
 '12232306015006': 1,
 '12232306015007': 1,
 '12232306015008': 1,
 '12232306015009': 1,
 '12232306015010': 1,
 '12232401015005': 1,
 '12232401015006': 1,
 '12232401015007': 1,
 '12232401015008': 1,
 '12232401015009': 1,
 '12232401015010': 1,
 '12232402015005': 1,
 '12232402015006': 1,
 '12232402015007': 1,
 '12232402015008': 1,
 '12232402015009': 1,
 '12232402015010': 1,
 '12232403015005': 1,
 '12232403015006': 1,
 '12232403015007': 1,
 '12232403015008': 1,
 '12232403015009': 1,
 '12232403015010': 1,
 '12232403023005': 1,
 '12232403023006': 1,
 '12232403023007': 1,
 '12232403023008': 1,
 '12232403023009': 1,
 '12232403023010': 1,
 '12232404015005': 1,
 '12232404015006': 1,
 '12232404015007': 1,
 '12232404015008': 1,
 '12232404015009': 1,
 '12232404015010': 1,
 '12232405015005': 1,
 '12232405015006': 1,
 '12232405015007': 1,
 '12232405015008': 1,
 '12232405015009': 1,
 '12232405015010': 1,
 '12232405023005': 1,
 '12232405023006': 1,
 '12232405023007': 1,
 '12232405023008': 1,
 '12232405023009': 1,
 '12232405023010': 1,
 '12232406015005': 1,
 '12232406015006': 1,
 '12232406015007': 1,
 '12232406015008': 1,
 '12232406015009': 1,
 '12232406015010': 1,
 '12232406023005': 1,
 '12232406023006': 1,
 '12232406023007': 1,
 '12232406023008': 1,
 '12232406023009': 1,
 '12232406023010': 1,
 '12232407015005': 1,
 '12232407015006': 1,
 '12232407015007': 1,
 '12232407015008': 1,
 '12232407015009': 1,
 '12232407015010': 1,
 '12232408005005': 1,
 '12232408005006': 1,
 '12232408005007': 1,
 '12232408005008': 1,
 '12232408005009': 1,
 '12232408005010': 1,
 '12232408015005': 1,
 '12232408015006': 1,
 '12232408015007': 1,
 '12232408015008': 1,
 '12232408015009': 1,
 '12232408015010': 1,
 '12232408023005': 1,
 '12232408023006': 1,
 '12232408023007': 1,
 '12232408023008': 1,
 '12232408023009': 1,
 '12232408023010': 1,
 '12232409015005': 1,
 '12232409015006': 1,
 '12232409015007': 1,
 '12232409015008': 1,
 '12232409015009': 1,
 '12232409015010': 1,
 '12232410015005': 1,
 '12232410015006': 1,
 '12232410015007': 1,
 '12232410015008': 1,
 '12232410015009': 1,
 '12232410015010': 1,
 '12232411022005': 1,
 '12232411022006': 1,
 '12232411022007': 1,
 '12232411022008': 1,
 '12232411022009': 1,
 '12232411022010': 1,
 '12232412015005': 1,
 '12232412015006': 1,
 '12232412015007': 1,
 '12232412015008': 1,
 '12232412015009': 1,
 '12232412015010': 1,
 '12232413015005': 1,
 '12232413015006': 1,
 '12232413015007': 1,
 '12232413015008': 1,
 '12232413015009': 1,
 '12232413015010': 1,
 '12232414028005': 1,
 '12232414028006': 1,
 '12232414028007': 1,
 '12232414028008': 1,
 '12232414028009': 1,
 '12232414028010': 1,
 '12232415003005': 1,
 '12232415003006': 1,
 '12232415003007': 1,
 '12232415003008': 1,
 '12232415003009': 1,
 '12232415003010': 1,
 '12232415015005': 1,
 '12232415015006': 1,
 '12232415015007': 1,
 '12232415015008': 1,
 '12232415015009': 1,
 '12232415015010': 1,
 '12232416009005': 1,
 '12232416009006': 1,
 '12232416009007': 1,
 '12232416009008': 1,
 '12232416009009': 1,
 '12232416009010': 1,
 '12232416015005': 1,
 '12232416015006': 1,
 '12232416015007': 1,
 '12232416015008': 1,
 '12232416015009': 1,
 '12232416015010': 1,
 '12232417015005': 1,
 '12232417015006': 1,
 '12232417015007': 1,
 '12232417015008': 1,
 '12232417015009': 1,
 '12232417015010': 1,
 '12232418009005': 1,
 '12232418009006': 1,
 '12232418009007': 1,
 '12232418009008': 1,
 '12232418009009': 1,
 '12232418009010': 1,
 '12232419003005': 1,
 '12232419003006': 1,
 '12232419003007': 1,
 '12232419003008': 1,
 '12232419003009': 1,
 '12232419003010': 1,
 '12232419015005': 1,
 '12232419015006': 1,
 '12232419015007': 1,
 '12232419015008': 1,
 '12232419015009': 1,
 '12232419015010': 1,
 '12232420003005': 1,
 '12232420003006': 1,
 '12232420003007': 1,
 '12232420003008': 1,
 '12232420003009': 1,
 '12232420003010': 1,
 '12232420015005': 1,
 '12232420015006': 1,
 '12232420015007': 1,
 '12232420015008': 1,
 '12232420015009': 1,
 '12232420015010': 1,
 '12232421015005': 1,
 '12232421015006': 1,
 '12232421015007': 1,
 '12232421015008': 1,
 '12232421015009': 1,
 '12232421015010': 1,
 '12232430015005': 1,
 '12232430015006': 1,
 '12232430015007': 1,
 '12232430015008': 1,
 '12232430015009': 1,
 '12232430015010': 1,
 '12232430023005': 1,
 '12232430023006': 1,
 '12232430023007': 1,
 '12232430023008': 1,
 '12232430023009': 1,
 '12232430023010': 1,
 '12232431023005': 1,
 '12232431023006': 1,
 '12232431023007': 1,
 '12232431023008': 1,
 '12232431023009': 1,
 '12232431023010': 1,
 '12232432015005': 1,
 '12232432015006': 1,
 '12232432015007': 1,
 '12232432015008': 1,
 '12232432015009': 1,
 '12232432015010': 1,
 '12232432023005': 1,
 '12232432023006': 1,
 '12232432023007': 1,
 '12232432023008': 1,
 '12232432023009': 1,
 '12232432023010': 1,
 '12232501003005': 1,
 '12232501003006': 1,
 '12232501003007': 1,
 '12232501003008': 1,
 '12232501003009': 1,
 '12232501003010': 1,
 '12232501009005': 1,
 '12232501009006': 1,
 '12232501009007': 1,
 '12232501009008': 1,
 '12232501009009': 1,
 '12232501009010': 1,
 '12232502015005': 1,
 '12232502015006': 1,
 '12232502015007': 1,
 '12232502015008': 1,
 '12232502015009': 1,
 '12232502015010': 1,
 '12233401015005': 1,
 '12233401015006': 1,
 '12233401015007': 1,
 '12233401015008': 1,
 '12233401015009': 1,
 '12233401015010': 1,
 '12233402015005': 1,
 '12233402015006': 1,
 '12233402015007': 1,
 '12233402015008': 1,
 '12233402015009': 1,
 '12233402015010': 1,
 '12233402030005': 1,

#### Cleaning year

In [8]:
year.head(5)

,Tipo Documento,Nº Documento,Tracking Number,Cliente,Rut Cliente,Condicion de Venta,Fecha Emisión,Fecha Vencimiento,Código Tributario,Fecha de generacion,Fecha de declaracion,Informado SII,Monto Neto Documento,Monto Impuestos Documento,Monto Exento Documento,Monto Documento,Monto Adeudado,ABONO DE CLIENTES,CHEQUE,CREDITO,EFECTIVO,FACTORING,Mercado Pago,NOTA CREDITO DEVOLUCION,TARJETA CREDITO,TARJETA DEBITO,TRANSFERENCIA BANCARIA,WEBPAY,Numero Comprobante Integrado,Nº Comprobante,Banco,Número,BancoValue,FACTURA COMPRA,FACTORING.1,Emisor,Vendedor,Sucursal,Estado,Orden de compra,Nota,Obser.,Nombre Contacto,Fono Contacto,Peso Neto,Peso Bruto,Volumen,PERIODO DEL SERVICIO,Marketplace,Nro. Orden,Total Descuentos,Total Doc. s/Descuentos,Descuentos Aplicados,Dirección,Ciudad,Comuna,Documentos Relacionados (Tipo Documento / Nº Documento / Fecha Emisión / Monto del documento ),Documentos de Referencia,Correo Cliente,Vuelto Forma de Pago,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,BOLETA ELECTRÓNICA T,39257,679d8d919190c8aa779c2102,natalia vergarag gaete,17635915-3,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-02-01 00:00:00,2025-01-31 00:00:00,Informado,14277,2713,0,16990,0,0,0,0,0,0,0,0,0,0,16990,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,2711967664,0,16990,No aplica,NaN,Santiago,Regi\u00f3n Metropolitana,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
1,BOLETA ELECTRÓNICA T,39256,679d81ebb99ccf26edeaa5f5,Nathaly Muñoz,16545211-9,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-02-01 00:00:00,2025-01-31 00:00:00,Informado,18374,3491,0,21865,0,0,0,0,0,0,0,0,0,0,21865,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vtex,1507460561103-01,0,21865,No aplica,NaN,NaN,NaN,NaN,NaN,nathalymunozsoto@gmail.com,0,NaN,NaN,NaN,NaN,NaN,NaN
2,BOLETA ELECTRÓNICA T,39255,679d80e6b99ccf26edeaa542,Sthefany Vilches Espinoza,17874155-1,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-02-01 00:00:00,2025-01-31 00:00:00,Informado,23521,4469,0,27990,0,0,0,0,0,0,0,0,0,0,27990,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,2711865080,0,27990,No aplica,NaN,Santiago,Regi\u00f3n Metropolitana,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
3,BOLETA ELECTRÓNICA T,39254,679d716c691a0b5ffe9a9bea,Paulina Zarate Gonzalez,13680930-K,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-02-01 00:00:00,2025-01-31 00:00:00,Informado,29403,5587,0,34990,0,0,0,0,0,0,0,0,0,0,34990,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,2711778354,0,34990,No aplica,NaN,Santiago,Regi\u00f3n Metropolitana,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
4,BOLETA ELECTRÓNICA T,39253,679d61189190c8aa779bf7cf,Marjorie Bravo,16297286-3,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-01-31 00:00:00,2025-01-31 00:00:00,Informado,50997,9690,0,60687,0,0,0,0,0,0,0,0,0,0,60687,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vtex,1507440561101-01,0,60687,No aplica,NaN,NaN,NaN,NaN,NaN,marjoriebravo83@gmail.com,0,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
year.tail(5)

,Tipo Documento,Nº Documento,Tracking Number,Cliente,Rut Cliente,Condicion de Venta,Fecha Emisión,Fecha Vencimiento,Código Tributario,Fecha de generacion,Fecha de declaracion,Informado SII,Monto Neto Documento,Monto Impuestos Documento,Monto Exento Documento,Monto Documento,Monto Adeudado,ABONO DE CLIENTES,CHEQUE,CREDITO,EFECTIVO,FACTORING,Mercado Pago,NOTA CREDITO DEVOLUCION,TARJETA CREDITO,TARJETA DEBITO,TRANSFERENCIA BANCARIA,WEBPAY,Numero Comprobante Integrado,Nº Comprobante,Banco,Número,BancoValue,FACTURA COMPRA,FACTORING.1,Emisor,Vendedor,Sucursal,Estado,Orden de compra,Nota,Obser.,Nombre Contacto,Fono Contacto,Peso Neto,Peso Bruto,Volumen,PERIODO DEL SERVICIO,Marketplace,Nro. Orden,Total Descuentos,Total Doc. s/Descuentos,Descuentos Aplicados,Dirección,Ciudad,Comuna,Documentos Relacionados (Tipo Documento / Nº Documento / Fecha Emisión / Monto del documento ),Documentos de Referencia,Correo Cliente,Vuelto Forma de Pago,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
19524,NOTA DE DÉBITO ELECTRÓNICA (3),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19525,Tipo Documento,Nº Documento,Tracking Number,Cliente,Rut Cliente,Fecha Emisión,Fecha Vencimiento,Código Tributario,Fecha de generacion,Fecha de declaracion,Informado SII,Monto Neto Documento,Monto Impuestos Documento,Monto Exento Documento,Monto Documento,ABONO DE CLIENTES,CHEQUE,CREDITO,EFECTIVO,FACTORING,Mercado Pago,NOTA CREDITO DEVOLUCION,TARJETA CREDITO,TARJETA DEBITO,TRANSFERENCIA BANCARIA,WEBPAY,Numero Comprobante Integrado,Nº Comprobante,Banco,Número,BancoValue,FACTURA COMPRA,FACTORING,Emisor,Vendedor,Sucursal,Estado,Orden de compra,Nota,Obser.,Nombre Contacto,Fono Contacto,Peso Neto,Peso Bruto,Volumen,PERIODO DEL SERVICIO,Marketplace,Nro. Orden,Dirección,Ciudad,Comuna,Documentos Relacionados (Tipo Documento / Nº Documento / Fecha Emisión / Monto del documento ),Documentos de Referencia,Correo Cliente,Vuelto Forma de Pago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19526,NOTA DE DÉBITO ELECTRÓNICA,10,NaN,CARCUR HERMANOS Y COMPANIA LIMITADA,80161100-1,2024-12-27 00:00:00,2024-12-27 00:00:00,56,2024-12-27 00:00:00,NaN,Por Informar,179358,34078,0,213436,119923,0,213436,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,Maria Mella,SUCURSAL MAYORISTA,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,JOSE LEYAN 748,TALAGANTE,TALAGANTE,[FACTURA ELECTRÓNICA/ 514/ 2024-09-02/ 306949][NOTA DE CRÉDITO ELECTRÓNICA/ 6150/ 2024-10-31/ 213436],NaN,carcur99@gmail.com,119923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19527,NOTA DE DÉBITO ELECTRÓNICA,9,NaN,Yuselys Munoz,26567490-9,2024-04-30 00:00:00,2024-04-30 00:00:00,56,2024-05-13 00:00:00,2024-05-13 00:00:00,Informado,12597,2393,0,14990,0,0,0,14990,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Centro,Santiago,Regi\u00f3n Metropolitana,[BOLETA ELECTRÓNICA T/ 27108/ 2024-03-24/ 14990][NOTA DE CRÉDITO ELECTRÓNICA/ 4466/ 2024-04-03/ 14990],NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19528,NOTA DE DÉBITO ELECTRÓNICA,8,NaN,Susana Triviño,18974141-3,2024-04-30 00:00:00,2024-04-30 00:00:00,56,2024-05-13 00:00:00,2024-05-13 00:00:00,Informado,5874,1116,0,6990,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STGO,Santiago,Regi\u00f3n Metropolitana,[BOLETA ELECTRÓNICA T/ 23780/ 2024-01-30/ 6990][NOTA DE CRÉDITO ELECTRÓNICA/ 4060/ 2024-02-29/ 6990],NaN,NaN,-6990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The datasets has multi tables.

In [10]:
Repeats_headers = ['Tipo Documento', 'Nº Documento', 'Rut Cliente']

# Identificar las filas donde aparecen los encabezados
header_indices = year[year['Tipo Documento'].isin(Repeats_headers)].index.tolist()

# Agregar la última fila como un límite para capturar la última tabla
header_indices.append(len(year))

# Lista donde guardaremos las tablas separadas
tables = []

# Verificar si hay una tabla antes del primer encabezado
if header_indices[0] > 0:
    first_table = year.iloc[:header_indices[0]].reset_index(drop=True)
    if not first_table.empty:
        tables.append(first_table)

# Separar las tablas detectadas y asignar los encabezados correctos
for i in range(len(header_indices) - 1):
    start = header_indices[i]  # Fila donde está el encabezado
    end = header_indices[i + 1]  # Hasta el siguiente encabezado

    # Extraer los datos y resetear el índice
    table = year.iloc[start:end].reset_index(drop=True)
    
    # Asignar la primera fila como encabezado
    table.columns = table.iloc[0]  # Convertir la primera fila en nombres de columnas
    table = table[1:].reset_index(drop=True)  # Eliminar la fila de encabezado original
    if i < 4:
        table=table.iloc[:-2]



    if not table.empty:
        tables.append(table)

columns_fill=["Documentos Relacionados (Tipo Documento / Nº Documento / Fecha Emisión / Monto del documento )",'Marketplace']

In [11]:
# Arrangements for Documentos Relacionados (Tipo Documento / Nº Documento / Fecha Emisión / Monto del documento )
for table in tables:
    table['Nº Documento'] =table['Nº Documento'].astype(str).str.strip()
    table[columns_fill] = table[columns_fill].fillna("Sin datos")
    table['Nº Documento new'] = table['Documentos Relacionados (Tipo Documento / Nº Documento / Fecha Emisión / Monto del documento )'].str.split('/').str[1]
    table['Nº Documento'] = table['Nº Documento'].str.replace('"', '').str.replace("'", "")


marketplace_dict=tables[0].set_index('Nº Documento')['Marketplace'].to_dict()

# search Nº Documento new (Nº Documento on dictionary) in the dictionary and take the value of the marketplace
tables[4]['Nº Documento new']=tables[4]['Nº Documento new'].astype(str).str.strip()
tables[4]['Marketplace'] = tables[4]['Nº Documento new'].map(marketplace_dict).fillna("Sin datos")
marketplace_dict.update(tables[4].set_index('Nº Documento')['Marketplace'].to_dict()) #update the dictionary with the new values
tables[4].head()

,Tipo Documento,Nº Documento,Tracking Number,Cliente,Rut Cliente,Fecha Emisión,Fecha Vencimiento,Código Tributario,Fecha de generacion,Fecha de declaracion,Informado SII,Monto Neto Documento,Monto Impuestos Documento,Monto Exento Documento,Monto Documento,Emisor,Vendedor,Sucursal,Estado,Orden de compra,Nota,Obser.,Nombre Contacto,Fono Contacto,Peso Neto,Peso Bruto,Volumen,PERIODO DEL SERVICIO,Marketplace,Nro. Orden,Dirección,Ciudad,Comuna,Documentos Relacionados (Tipo Documento / Nº Documento / Fecha Emisión / Monto del documento ),Documentos de Referencia,Correo Cliente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nº Documento new
0,NOTA DE CRÉDITO ELECTRÓNICA,6827,NaN,Marie Helene Ducheylard,10251278-2,2025-01-31 00:00:00,2025-01-31 00:00:00,61,2025-02-10 00:00:00,2025-02-10 00:00:00,Informado,20992,3988,0,24980,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ripley,NaN,STGO,STGO,STGO,[BOLETA ELECTRÓNICA T/ 38978/ 2025-01-26/ 24980],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38978
1,NOTA DE CRÉDITO ELECTRÓNICA,6826,NaN,Pamela Del Carmen Pena Munoz,15393062-7,2025-01-31 00:00:00,2025-01-31 00:00:00,61,2025-02-10 00:00:00,2025-02-10 00:00:00,Informado,34445,6545,0,40990,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ripley,NaN,STGO,STGO,STGO,[BOLETA ELECTRÓNICA T/ 38902/ 2025-01-24/ 41980],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38902
2,NOTA DE CRÉDITO ELECTRÓNICA,6825,NaN,Cecilia Riquelme,9748952-1,2025-01-31 00:00:00,2025-01-31 00:00:00,61,2025-02-10 00:00:00,2025-02-10 00:00:00,Informado,19319,3671,0,22990,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ripley,NaN,STGO,STGO,STGO,[BOLETA ELECTRÓNICA T/ 38594/ 2025-01-17/ 23980],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38594
3,NOTA DE CRÉDITO ELECTRÓNICA,6824,NaN,Jeannette Vera,10051231-9,2025-01-31 00:00:00,2025-01-31 00:00:00,61,2025-02-10 00:00:00,2025-02-10 00:00:00,Informado,32756,6224,0,38980,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ripley,NaN,STGO,STGO,STGO,[BOLETA ELECTRÓNICA T/ 38369/ 2025-01-13/ 38980],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38369
4,NOTA DE CRÉDITO ELECTRÓNICA,6822,NaN,Karim Lazo,12465332-0,2025-01-31 00:00:00,2025-01-31 00:00:00,61,2025-02-08 00:00:00,2025-02-08 00:00:00,Informado,17639,3351,0,20990,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ripley,NaN,STGO,STGO,STGO,[BOLETA ELECTRÓNICA T/ 38175/ 2025-01-09/ 20990],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38175

In [12]:
# Now for the other tables
tables[5]['Nº Documento new']=tables[5]['Nº Documento new'].astype(str).str.strip()
tables[5]['Marketplace'] = tables[5]['Nº Documento new'].map(marketplace_dict).fillna("Sin datos")
marketplace_dict.update(tables[5].set_index('Nº Documento')['Marketplace'].to_dict())

tables[1]['Nº Documento new']=tables[1]['Nº Documento new'].astype(str).str.strip()
tables[1]['Marketplace'] = tables[1]['Nº Documento new'].map(marketplace_dict).fillna("Sin datos")
marketplace_dict.update(tables[1].set_index('Nº Documento')['Marketplace'].to_dict())


tables[2]['Nº Documento new']=tables[2]['Nº Documento new'].astype(str).str.strip()
tables[2]['Marketplace'] = tables[2]['Nº Documento new'].map(marketplace_dict).fillna("Sin datos")
marketplace_dict.update(tables[2].set_index('Nº Documento')['Marketplace'].to_dict())


tables[3]['Nº Documento new']=tables[3]['Nº Documento new'].astype(str).str.strip()
tables[3]['Marketplace'] = tables[3]['Nº Documento new'].map(marketplace_dict).fillna("Sin datos")
marketplace_dict.update(tables[3].set_index('Nº Documento')['Marketplace'].to_dict())
tables[3].head()
principal.head(5)

,Tipo Movimiento,Sucursal,Vendedor,Cliente,Rut Cliente,Tipo de Documento,Numero Documento,Tracking Number,Fecha Documento,Fecha y Hora Venta,Lista de Precio,Tipo de Producto / Servicio,SKU,Producto / Servicio,Variante,Otros Atributos,Precio Neto Unitario,Cantidad,Subtotal Impuestos,Subtotal Bruto,Costo Neto Unitario,Margen,Costo Total Neto,% Margen,Detalle de Productos/Servicios Pack/Promo,Dirección Cliente,Comuna Cliente,Ciudad Cliente,Email Cliente
0,Venta,Casa Matriz,VENTA ONLINE,Catalina Cusó,20415182-2,boleta electrónica t,37678.0,6774be78b0bd82e806fb1398,01/01/2025,01/01/2025 01:03 AM,Lista de Precios Base,Sandalia,2.253360e+13,Via Uno Sandalia 22533601 Crema,36,NaN,21845,1.0,4150,25996,15954.0,5892,15954.0,37,NaN,NaN,NaN,NaN,cata0cuso@gmail.com
1,Venta,Casa Matriz,VENTA ONLINE,Catalina Cusó,20415182-2,boleta electrónica t,37678.0,6774be78b0bd82e806fb1398,01/01/2025,01/01/2025 01:03 AM,Lista de Precios Base,Sin Tipo,1.735704e+09,Glosa,Despacho,NaN,5876,1.0,1117,6993,0.0,5876,0.0,100,NaN,NaN,NaN,NaN,cata0cuso@gmail.com
2,Venta,Casa Matriz,VENTA ONLINE,Antonia Muñoz Reymond,16365935-2,boleta electrónica t,37679.0,6774cc4ab0bd82e806fb1601,01/01/2025,01/01/2025 02:02 AM,Lista de Precios Base,Sandalia,2.250160e+13,Via Uno Sandalia 22501603 Negro,37,NaN,17639,1.0,3351,20990,10405.0,7234,10405.0,70,NaN,NaN,NaN,NaN,antoniamr@gmail.com
3,Venta,Casa Matriz,VENTA ONLINE,Johanna Quitral Henriquez,13912101-5,boleta electrónica t,37680.0,6774e19a6a3f329377f8eaf5,01/01/2025,01/01/2025 03:32 AM,Lista de Precios Base,Sandalia,2.254161e+13,Via Uno Sandalia 22541607 Negro,39,NaN,15123,1.0,2873,17996,8400.0,6723,8400.0,80,NaN,NaN,NaN,NaN,johannaquitralh@gmail.com
4,Venta,Casa Matriz,VENTA ONLINE,Johanna Quitral Henriquez,13912101-5,boleta electrónica t,37680.0,6774e19a6a3f329377f8eaf5,01/01/2025,01/01/2025 03:32 AM,Lista de Precios Base,Sandalia,2.254160e+13,Via Uno Sandalia 22541603 Negro,36,NaN,18903,1.0,3592,22495,11075.0,7828,11075.0,71,NaN,NaN,NaN,NaN,johannaquitralh@gmail.com

In [13]:
tables[0].head(5)

,Tipo Documento,Nº Documento,Tracking Number,Cliente,Rut Cliente,Condicion de Venta,Fecha Emisión,Fecha Vencimiento,Código Tributario,Fecha de generacion,Fecha de declaracion,Informado SII,Monto Neto Documento,Monto Impuestos Documento,Monto Exento Documento,Monto Documento,Monto Adeudado,ABONO DE CLIENTES,CHEQUE,CREDITO,EFECTIVO,FACTORING,Mercado Pago,NOTA CREDITO DEVOLUCION,TARJETA CREDITO,TARJETA DEBITO,TRANSFERENCIA BANCARIA,WEBPAY,Numero Comprobante Integrado,Nº Comprobante,Banco,Número,BancoValue,FACTURA COMPRA,FACTORING.1,Emisor,Vendedor,Sucursal,Estado,Orden de compra,Nota,Obser.,Nombre Contacto,Fono Contacto,Peso Neto,Peso Bruto,Volumen,PERIODO DEL SERVICIO,Marketplace,Nro. Orden,Total Descuentos,Total Doc. s/Descuentos,Descuentos Aplicados,Dirección,Ciudad,Comuna,Documentos Relacionados (Tipo Documento / Nº Documento / Fecha Emisión / Monto del documento ),Documentos de Referencia,Correo Cliente,Vuelto Forma de Pago,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Nº Documento new
0,BOLETA ELECTRÓNICA T,39257,679d8d919190c8aa779c2102,natalia vergarag gaete,17635915-3,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-02-01 00:00:00,2025-01-31 00:00:00,Informado,14277,2713,0,16990,0,0,0,0,0,0,0,0,0,0,16990,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,2711967664,0,16990,No aplica,NaN,Santiago,Regi\u00f3n Metropolitana,Sin datos,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BOLETA ELECTRÓNICA T,39256,679d81ebb99ccf26edeaa5f5,Nathaly Muñoz,16545211-9,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-02-01 00:00:00,2025-01-31 00:00:00,Informado,18374,3491,0,21865,0,0,0,0,0,0,0,0,0,0,21865,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vtex,1507460561103-01,0,21865,No aplica,NaN,NaN,NaN,Sin datos,NaN,nathalymunozsoto@gmail.com,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BOLETA ELECTRÓNICA T,39255,679d80e6b99ccf26edeaa542,Sthefany Vilches Espinoza,17874155-1,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-02-01 00:00:00,2025-01-31 00:00:00,Informado,23521,4469,0,27990,0,0,0,0,0,0,0,0,0,0,27990,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,2711865080,0,27990,No aplica,NaN,Santiago,Regi\u00f3n Metropolitana,Sin datos,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BOLETA ELECTRÓNICA T,39254,679d716c691a0b5ffe9a9bea,Paulina Zarate Gonzalez,13680930-K,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-02-01 00:00:00,2025-01-31 00:00:00,Informado,29403,5587,0,34990,0,0,0,0,0,0,0,0,0,0,34990,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,2711778354,0,34990,No aplica,NaN,Santiago,Regi\u00f3n Metropolitana,Sin datos,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BOLETA ELECTRÓNICA T,39253,679d61189190c8aa779bf7cf,Marjorie Bravo,16297286-3,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-01-31 00:00:00,2025-01-31 00:00:00,Informado,50997,9690,0,60687,0,0,0,0,0,0,0,0,0,0,60687,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vtex,1507440561101-01,0,60687,No aplica,NaN,NaN,NaN,Sin datos,NaN,marjoriebravo83@gmail.com,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:

# Repeat but with the dictionary updated
for table in tables:
    table['Nº Documento'] =table['Nº Documento'].astype(str).str.strip()
    table['Nº Documento new']=table['Nº Documento new'].astype(str).str.strip()
    table.loc[table['Marketplace'] == "Sin datos", 'Marketplace'] = table.loc[table['Marketplace'] == "Sin datos", 'Nº Documento new'].map(marketplace_dict).fillna("Sin datos")

# Concatenate all the tables
for i in range(len(tables)):
    # Eliminar columnas duplicadas dejando solo la primera ocurrencia
    tables[i] = tables[i].loc[:, ~tables[i].columns.duplicated()]
tables = [table.reset_index(drop=True) for table in tables]
final_table = pd.concat(tables, ignore_index=True, sort=False)
final_table= final_table.loc[:, ~pd.isna(final_table.columns)]
final_table.tail(5)

,Tipo Documento,Nº Documento,Tracking Number,Cliente,Rut Cliente,Condicion de Venta,Fecha Emisión,Fecha Vencimiento,Código Tributario,Fecha de generacion,Fecha de declaracion,Informado SII,Monto Neto Documento,Monto Impuestos Documento,Monto Exento Documento,Monto Documento,Monto Adeudado,ABONO DE CLIENTES,CHEQUE,CREDITO,EFECTIVO,FACTORING,Mercado Pago,NOTA CREDITO DEVOLUCION,TARJETA CREDITO,TARJETA DEBITO,TRANSFERENCIA BANCARIA,WEBPAY,Numero Comprobante Integrado,Nº Comprobante,Banco,Número,BancoValue,FACTURA COMPRA,FACTORING.1,Emisor,Vendedor,Sucursal,Estado,Orden de compra,Nota,Obser.,Nombre Contacto,Fono Contacto,Peso Neto,Peso Bruto,Volumen,PERIODO DEL SERVICIO,Marketplace,Nro. Orden,Total Descuentos,Total Doc. s/Descuentos,Descuentos Aplicados,Dirección,Ciudad,Comuna,Documentos Relacionados (Tipo Documento / Nº Documento / Fecha Emisión / Monto del documento ),Documentos de Referencia,Correo Cliente,Vuelto Forma de Pago,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Nº Documento new,Clausula de Venta,Monto Clausula,Modalidad Venta,Via Transporte,Total de Bultos,Pais Destino,Tipo de Despacho,Sucursal de Destino
19511,NOTA DE CRÉDITO ELECTRÓNICA,3427,NaN,victoria carrasco,11844669-0,NaN,2024-02-01 00:00:00,2024-02-01 00:00:00,61,2024-02-01 00:00:00,2024-02-01 00:00:00,Informado,20151,3829,0,23980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sin datos,NaN,NaN,NaN,NaN,NaN,Santiago,Regi\u00f3n Metropolitana,[BOLETA ELECTRÓNICA T/ 22885/ 2024-01-13/ 23980],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19512,NOTA DE CRÉDITO ELECTRÓNICA,3421,NaN,jezabel mella,17395619-3,NaN,2024-02-01 00:00:00,2024-02-01 00:00:00,61,2024-02-01 00:00:00,2024-02-01 00:00:00,Informado,10076,1914,0,11990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sin datos,NaN,NaN,NaN,NaN,NaN,Santiago,Regi\u00f3n Metropolitana,[BOLETA ELECTRÓNICA T/ 23429/ 2024-01-23/ 11990],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19513,NOTA DE DÉBITO ELECTRÓNICA,10,NaN,CARCUR HERMANOS Y COMPANIA LIMITADA,80161100-1,NaN,2024-12-27 00:00:00,2024-12-27 00:00:00,56,2024-12-27 00:00:00,NaN,Por Informar,179358,34078,0,213436,NaN,119923,0,213436,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,Maria Mella,SUCURSAL MAYORISTA,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sin datos,NaN,NaN,NaN,NaN,JOSE LEYAN 748,TALAGANTE,TALAGANTE,[FACTURA ELECTRÓNICA/ 514/ 2024-09-02/ 306949][NOTA DE CRÉDITO ELECTRÓNICA/ 6150/ 2024-10-31/ 213436],NaN,carcur99@gmail.com,119923,NaN,NaN,NaN,NaN,NaN,NaN,514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19514,NOTA DE DÉBITO ELECTRÓNICA,9,NaN,Yuselys Munoz,26567490-9,NaN,2024-04-30 00:00:00,2024-04-30 00:00:00,56,2024-05-13 00:00:00,2024-05-13 00:00:00,Informado,12597,2393,0,14990,NaN,0,0,0,14990,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,NaN,NaN,NaN,NaN,Centro,Santiago,Regi\u00f3n Metropolitana,[BOLETA ELECTRÓNICA T/ 27108/ 2024-03-24/ 14990][NOTA DE CRÉDITO ELECTRÓNICA/ 4466/ 2024-04-03/ 14990],NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,27108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19515,NOTA DE DÉBITO ELECTRÓNICA,8,NaN,Susana Triviño,18974141-3,NaN,2024-04-30 00:00:00,2024-04-30 00:00:00,56,2024-05-13 00:00:00,2024-05-13 00:00:00,Informado,5874,1116,0,6990,NaN,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sin datos,NaN,NaN,NaN,NaN,STGO,Santiago,Regi\u00f3n Metropolitana,[BOLETA ELECTRÓNICA T/ 23780/ 2024-01-30/ 6990][NOTA DE CRÉDITO ELECTRÓNICA/ 4060/ 2024-02-29/ 6990],NaN,NaN,-6990,NaN,NaN,NaN,NaN,NaN,NaN,23780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Set on tables conditions for Marketplace

In [15]:


# Set on facturas when Sucursal is SUCURSAL MAYORISTA set Marketplace as vpm
final_table['Marketplace'] = np.where(
    (final_table['Sucursal'] == 'SUCURSAL MAYORISTA') & 
    (final_table['Marketplace'] == 'Sin datos') & (final_table['Tipo Documento'] != 'BOLETA ELECTRÓNICA T'),
    'vpm',
    final_table['Marketplace']
)

# Set on facturas when Vendedor is VENTA ONLINE set Marketplace as fcom
final_table['Marketplace'] = np.where(
    (final_table['Vendedor'] == 'VENTA ONLINE') & 
    (final_table['Marketplace'] == 'Sin datos'),
    'fcom',
    final_table['Marketplace']
)

# Set on facturas when Sucursal is SUCURSAL MAYORISTA and BOLETA ELECTRÓNICA T set Marketplace as T.NAVIDEÑA
final_table['Marketplace'] = np.where(
    (final_table['Sucursal'] == 'SUCURSAL MAYORISTA') & 
    (final_table['Marketplace'] == 'Sin datos') & (final_table['Tipo Documento'] == 'BOLETA ELECTRÓNICA T'),
    'T.NAVIDEÑA',
    final_table['Marketplace']
)

# Set on facturas when Tipo Documento is FACTURA DE EXPORTACIÓN ELECTRÓNICA set Marketplace as cvd
final_table['Marketplace'] = np.where(
    (final_table['Tipo Documento'] == 'FACTURA DE EXPORTACIÓN ELECTRÓNICA') & 
    (final_table['Marketplace'] == 'Sin datos'),
    'cvd',
    final_table['Marketplace']
)

final_table.head()

# Verify conditions
print(final_table.loc[final_table['Tipo Documento'] == 'FACTURA DE EXPORTACIÓN ELECTRÓNICA', 'Marketplace'].value_counts())
print(final_table.loc[final_table['Vendedor'] == 'VENTA ONLINE', 'Marketplace'].value_counts())
print(final_table.loc[final_table['Sucursal'] == 'SUCURSAL MAYORISTA', 'Marketplace'].value_counts())
print(final_table.loc[(final_table['Sucursal'] == 'SUCURSAL MAYORISTA') & (final_table['Tipo Documento'] == 'BOLETA ELECTRÓNICA T'), 'Marketplace'].value_counts())



# Last update of the dictionary
marketplace_dict.update(final_table.set_index('Nº Documento')['Marketplace'].to_dict())

Marketplace
cvd    7
Name: count, dtype: int64
Marketplace
fcom      9510
vtex      7290
paris     1091
ripley     544
vpm        137
Name: count, dtype: int64
Marketplace
T.NAVIDEÑA    585
vpm           321
Name: count, dtype: int64
Marketplace
T.NAVIDEÑA    585
Name: count, dtype: int64

In [16]:
final_table[(final_table['Vendedor'] == 'VENTA ONLINE') & (final_table['Marketplace'] == 'fcom')].head() # Check if the condition is met

,Tipo Documento,Nº Documento,Tracking Number,Cliente,Rut Cliente,Condicion de Venta,Fecha Emisión,Fecha Vencimiento,Código Tributario,Fecha de generacion,Fecha de declaracion,Informado SII,Monto Neto Documento,Monto Impuestos Documento,Monto Exento Documento,Monto Documento,Monto Adeudado,ABONO DE CLIENTES,CHEQUE,CREDITO,EFECTIVO,FACTORING,Mercado Pago,NOTA CREDITO DEVOLUCION,TARJETA CREDITO,TARJETA DEBITO,TRANSFERENCIA BANCARIA,WEBPAY,Numero Comprobante Integrado,Nº Comprobante,Banco,Número,BancoValue,FACTURA COMPRA,FACTORING.1,Emisor,Vendedor,Sucursal,Estado,Orden de compra,Nota,Obser.,Nombre Contacto,Fono Contacto,Peso Neto,Peso Bruto,Volumen,PERIODO DEL SERVICIO,Marketplace,Nro. Orden,Total Descuentos,Total Doc. s/Descuentos,Descuentos Aplicados,Dirección,Ciudad,Comuna,Documentos Relacionados (Tipo Documento / Nº Documento / Fecha Emisión / Monto del documento ),Documentos de Referencia,Correo Cliente,Vuelto Forma de Pago,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Nº Documento new,Clausula de Venta,Monto Clausula,Modalidad Venta,Via Transporte,Total de Bultos,Pais Destino,Tipo de Despacho,Sucursal de Destino
0,BOLETA ELECTRÓNICA T,39257,679d8d919190c8aa779c2102,natalia vergarag gaete,17635915-3,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-02-01 00:00:00,2025-01-31 00:00:00,Informado,14277,2713,0,16990,0,0,0,0,0,0,0,0,0,0,16990,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,2711967664,0,16990,No aplica,NaN,Santiago,Regi\u00f3n Metropolitana,Sin datos,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BOLETA ELECTRÓNICA T,39255,679d80e6b99ccf26edeaa542,Sthefany Vilches Espinoza,17874155-1,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-02-01 00:00:00,2025-01-31 00:00:00,Informado,23521,4469,0,27990,0,0,0,0,0,0,0,0,0,0,27990,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,2711865080,0,27990,No aplica,NaN,Santiago,Regi\u00f3n Metropolitana,Sin datos,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BOLETA ELECTRÓNICA T,39254,679d716c691a0b5ffe9a9bea,Paulina Zarate Gonzalez,13680930-K,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-02-01 00:00:00,2025-01-31 00:00:00,Informado,29403,5587,0,34990,0,0,0,0,0,0,0,0,0,0,34990,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,2711778354,0,34990,No aplica,NaN,Santiago,Regi\u00f3n Metropolitana,Sin datos,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,BOLETA ELECTRÓNICA T,39249,679d42956ce473e7e7fc9b14,Laarni Lazalita,24885149-K,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-01-31 00:00:00,2025-01-31 00:00:00,Informado,16798,3192,0,19990,0,0,0,0,0,0,0,0,0,0,19990,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,2711564587,0,19990,No aplica,Centro,Santiago,Regi\u00f3n Metropolitana,Sin datos,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,BOLETA ELECTRÓNICA T,39246,679d3fd4c9a6db8c95035c9d,Belen Rodriguez Arriaza,17441650-8,Al día,2025-01-31 00:00:00,2025-01-31 00:00:00,39,2025-01-31 00:00:00,2025-01-31 00:00:00,Informado,14277,2713,0,16990,0,0,0,0,0,0,0,0,0,0,16990,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Mateo Spa ONLINE,VENTA ONLINE,Casa Matriz,Vigente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fcom,2711550183,0,16990,No aplica,Centro,Santiago,Regi\u00f3n Metropolitana,Sin datos,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Working with principal

First we need to combine dictionarys with principal

In [17]:
# Clean principal
principal= principal.iloc[:-1] #Eliminate the last row
principal['SKU'] = principal['SKU'].astype(int).astype(str)
principal['SKU'] = principal['SKU'].str.replace('"', '', regex=False)
principal['SKU'] = principal['SKU'].str.strip()
principal['Costo Neto Unitario']=principal['Costo Neto Unitario'].astype(int)
principal['Cantidad']=principal['Cantidad'].astype(int)
principal['Costo Total Neto']=principal['Costo Total Neto'].astype(int)
principal['Numero Documento']=principal['Numero Documento'].astype(int).astype(str)
principal['Detalle de Productos/Servicios Pack/Promo']=principal['Detalle de Productos/Servicios Pack/Promo'].fillna(0).astype(int)

# fill NAN values when is object with "Sin datos"
principal[principal.select_dtypes(include='object').columns] = principal.select_dtypes(include='object').fillna("Sin datos")

# Costo Neto Unitario and Costo Total Neto are negative for boleta electrónica t
principal.loc[principal['Tipo de Documento'] == 'boleta electrónica t', ['Costo Neto Unitario', 'Costo Total Neto']] *= -1

principal.info()
principal.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3131 entries, 0 to 3130
Data columns (total 29 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Tipo Movimiento                            3131 non-null   object
 1   Sucursal                                   3131 non-null   object
 2   Vendedor                                   3131 non-null   object
 3   Cliente                                    3131 non-null   object
 4   Rut Cliente                                3131 non-null   object
 5   Tipo de Documento                          3131 non-null   object
 6   Numero Documento                           3131 non-null   object
 7   Tracking Number                            3131 non-null   object
 8   Fecha Documento                            3131 non-null   object
 9   Fecha y Hora Venta                         3131 non-null   object
 10  Lista de Precio                            3131 non-null   object
 11  Tipo de Producto / Servicio                3131 non-null   object
 12  SKU                                        3131 non-null   object
 13  Producto / Servicio                        3131 non-null   object
 14  Variante                                   3131 non-null   object
 15  Otros Atributos                            0 non-null      float64
 16  Precio Neto Unitario                       3131 non-null   int64
 17  Cantidad                                   3131 non-null   int64
 18  Subtotal Impuestos                         3131 non-null   int64
 19  Subtotal Bruto                             3131 non-null   int64
 20  Costo Neto Unitario                        3131 non-null   int64
 21  Margen                                     3131 non-null   int64
 22  Costo Total Neto                           3131 non-null   int64
 23  % Margen                                   3131 non-null   int64
 24  Detalle de Productos/Servicios Pack/Promo  3131 non-null   int64
 25  Dirección Cliente                          3131 non-null   object
 26  Comuna Cliente                             3131 non-null   object
 27  Ciudad Cliente                             3131 non-null   object
 28  Email Cliente                              3131 non-null   object
dtypes: float64(1), int64(9), object(19)
memory usage: 709.5+ KB

,Tipo Movimiento,Sucursal,Vendedor,Cliente,Rut Cliente,Tipo de Documento,Numero Documento,Tracking Number,Fecha Documento,Fecha y Hora Venta,Lista de Precio,Tipo de Producto / Servicio,SKU,Producto / Servicio,Variante,Otros Atributos,Precio Neto Unitario,Cantidad,Subtotal Impuestos,Subtotal Bruto,Costo Neto Unitario,Margen,Costo Total Neto,% Margen,Detalle de Productos/Servicios Pack/Promo,Dirección Cliente,Comuna Cliente,Ciudad Cliente,Email Cliente
0,Venta,Casa Matriz,VENTA ONLINE,Catalina Cusó,20415182-2,boleta electrónica t,37678,6774be78b0bd82e806fb1398,01/01/2025,01/01/2025 01:03 AM,Lista de Precios Base,Sandalia,22533601009006,Via Uno Sandalia 22533601 Crema,36,NaN,21845,1,4150,25996,-15954,5892,-15954,37,0,Sin datos,Sin datos,Sin datos,cata0cuso@gmail.com
1,Venta,Casa Matriz,VENTA ONLINE,Catalina Cusó,20415182-2,boleta electrónica t,37678,6774be78b0bd82e806fb1398,01/01/2025,01/01/2025 01:03 AM,Lista de Precios Base,Sin Tipo,1735704183,Glosa,Despacho,NaN,5876,1,1117,6993,0,5876,0,100,0,Sin datos,Sin datos,Sin datos,cata0cuso@gmail.com
2,Venta,Casa Matriz,VENTA ONLINE,Antonia Muñoz Reymond,16365935-2,boleta electrónica t,37679,6774cc4ab0bd82e806fb1601,01/01/2025,01/01/2025 02:02 AM,Lista de Precios Base,Sandalia,22501603015007,Via Uno Sandalia 22501603 Negro,37,NaN,17639,1,3351,20990,-10405,7234,-10405,70,0,Sin datos,Sin datos,Sin datos,antoniamr@gmail.com
3,Venta,Casa Matriz,VENTA ONLINE,Johanna Quitral Henriquez,13912101-5,boleta electrónica t,37680,6774e19a6a3f329377f8eaf5,01/01/2025,01/01/2025 03:32 AM,Lista de Precios Base,Sandalia,22541607015009,Via Uno Sandalia 22541607 Negro,39,NaN,15123,1,2873,17996,-8400,6723,-8400,80,0,Sin datos,Sin datos,Sin datos,johannaquitralh@gmail.com
4,Venta,Casa Matriz,VENTA ONLINE,Johanna Quitral Henriquez,13912101-5,boleta electrónica t,37680,6774e19a6a3f329377f8eaf5,01/01/2025,01/01/2025 03:32 AM,Lista de Precios Base,Sandalia,22541603015006,Via Uno Sandalia 22541603 Negro,36,NaN,18903,1,3592,22495,-11075,7828,-11075,71,0,Sin datos,Sin datos,Sin datos,johannaquitralh@gmail.com

In [18]:
# For principal put dictionary of cost
principal.loc[(principal['Costo Neto Unitario'] == 0) & principal['SKU'].notna(), 'Costo Neto Unitario'] = (
    principal['SKU'].map(cost_dict))
principal['Costo Neto Unitario']=principal['Costo Neto Unitario'].fillna(0)
principal['Costo Neto Unitario']=principal['Costo Neto Unitario'].astype(int)
principal.tail()

,Tipo Movimiento,Sucursal,Vendedor,Cliente,Rut Cliente,Tipo de Documento,Numero Documento,Tracking Number,Fecha Documento,Fecha y Hora Venta,Lista de Precio,Tipo de Producto / Servicio,SKU,Producto / Servicio,Variante,Otros Atributos,Precio Neto Unitario,Cantidad,Subtotal Impuestos,Subtotal Bruto,Costo Neto Unitario,Margen,Costo Total Neto,% Margen,Detalle de Productos/Servicios Pack/Promo,Dirección Cliente,Comuna Cliente,Ciudad Cliente,Email Cliente
3126,Devolucion,Casa Matriz,VENTA ONLINE,Cecilia Riquelme,9748952-1,nota de crédito electrónica,6825,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737160877,Glosa,Despacho,NaN,-5042,0,-958,-6000,0,-5042,0,100,0,STGO,STGO,STGO,Sin datos
3127,Devolucion,Casa Matriz,VENTA ONLINE,Pamela Del Carmen Pena Munoz,15393062-7,nota de crédito electrónica,6826,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Bota,22513301003009,Via Uno Bota 22513301 Beige,39,NaN,-30244,0,-5747,-35990,20372,-30243,0,100,0,STGO,STGO,STGO,Sin datos
3128,Devolucion,Casa Matriz,VENTA ONLINE,Pamela Del Carmen Pena Munoz,15393062-7,nota de crédito electrónica,6826,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737728789,Glosa,Despacho,NaN,-4202,0,-798,-5000,0,-4202,0,100,0,STGO,STGO,STGO,Sin datos
3129,Devolucion,Casa Matriz,VENTA ONLINE,Marie Helene Ducheylard,10251278-2,nota de crédito electrónica,6827,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sandalia,22501603004005,Via Uno Sandalia 22501603 Blanco,35,NaN,-17639,0,-3351,-20990,10405,-17639,0,100,0,STGO,STGO,STGO,Sin datos
3130,Devolucion,Casa Matriz,VENTA ONLINE,Marie Helene Ducheylard,10251278-2,nota de crédito electrónica,6827,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737902477,Glosa,Despacho,NaN,-3353,0,-637,-3990,0,-3353,0,100,0,STGO,STGO,STGO,Sin datos

In [19]:
# For principal put dictionary of count
principal.loc[(principal['Cantidad'] == 0) & principal['SKU'].notna(), 'Cantidad'] = (
    principal['SKU'].map(count_dict))
principal['Cantidad']=principal['Cantidad'].fillna(0)
principal['Cantidad']=principal['Cantidad'].astype(int)
principal.tail()

,Tipo Movimiento,Sucursal,Vendedor,Cliente,Rut Cliente,Tipo de Documento,Numero Documento,Tracking Number,Fecha Documento,Fecha y Hora Venta,Lista de Precio,Tipo de Producto / Servicio,SKU,Producto / Servicio,Variante,Otros Atributos,Precio Neto Unitario,Cantidad,Subtotal Impuestos,Subtotal Bruto,Costo Neto Unitario,Margen,Costo Total Neto,% Margen,Detalle de Productos/Servicios Pack/Promo,Dirección Cliente,Comuna Cliente,Ciudad Cliente,Email Cliente
3126,Devolucion,Casa Matriz,VENTA ONLINE,Cecilia Riquelme,9748952-1,nota de crédito electrónica,6825,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737160877,Glosa,Despacho,NaN,-5042,0,-958,-6000,0,-5042,0,100,0,STGO,STGO,STGO,Sin datos
3127,Devolucion,Casa Matriz,VENTA ONLINE,Pamela Del Carmen Pena Munoz,15393062-7,nota de crédito electrónica,6826,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Bota,22513301003009,Via Uno Bota 22513301 Beige,39,NaN,-30244,1,-5747,-35990,20372,-30243,0,100,0,STGO,STGO,STGO,Sin datos
3128,Devolucion,Casa Matriz,VENTA ONLINE,Pamela Del Carmen Pena Munoz,15393062-7,nota de crédito electrónica,6826,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737728789,Glosa,Despacho,NaN,-4202,0,-798,-5000,0,-4202,0,100,0,STGO,STGO,STGO,Sin datos
3129,Devolucion,Casa Matriz,VENTA ONLINE,Marie Helene Ducheylard,10251278-2,nota de crédito electrónica,6827,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sandalia,22501603004005,Via Uno Sandalia 22501603 Blanco,35,NaN,-17639,1,-3351,-20990,10405,-17639,0,100,0,STGO,STGO,STGO,Sin datos
3130,Devolucion,Casa Matriz,VENTA ONLINE,Marie Helene Ducheylard,10251278-2,nota de crédito electrónica,6827,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737902477,Glosa,Despacho,NaN,-3353,0,-637,-3990,0,-3353,0,100,0,STGO,STGO,STGO,Sin datos

In [20]:
# Quantities for nota de crédito electrónica are negative
principal.loc[principal['Tipo de Documento'] == 'nota de crédito electrónica', 'Cantidad'] *= -1

# Obtain the total cost (for notas de crédito electrónica the cost and total cost are positive)
principal.loc[principal['Tipo de Documento'] == 'nota de crédito electrónica', 'Costo Total Neto'] = abs(
    principal['Costo Neto Unitario'] * principal['Cantidad']
)

principal.tail()

,Tipo Movimiento,Sucursal,Vendedor,Cliente,Rut Cliente,Tipo de Documento,Numero Documento,Tracking Number,Fecha Documento,Fecha y Hora Venta,Lista de Precio,Tipo de Producto / Servicio,SKU,Producto / Servicio,Variante,Otros Atributos,Precio Neto Unitario,Cantidad,Subtotal Impuestos,Subtotal Bruto,Costo Neto Unitario,Margen,Costo Total Neto,% Margen,Detalle de Productos/Servicios Pack/Promo,Dirección Cliente,Comuna Cliente,Ciudad Cliente,Email Cliente
3126,Devolucion,Casa Matriz,VENTA ONLINE,Cecilia Riquelme,9748952-1,nota de crédito electrónica,6825,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737160877,Glosa,Despacho,NaN,-5042,0,-958,-6000,0,-5042,0,100,0,STGO,STGO,STGO,Sin datos
3127,Devolucion,Casa Matriz,VENTA ONLINE,Pamela Del Carmen Pena Munoz,15393062-7,nota de crédito electrónica,6826,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Bota,22513301003009,Via Uno Bota 22513301 Beige,39,NaN,-30244,-1,-5747,-35990,20372,-30243,20372,100,0,STGO,STGO,STGO,Sin datos
3128,Devolucion,Casa Matriz,VENTA ONLINE,Pamela Del Carmen Pena Munoz,15393062-7,nota de crédito electrónica,6826,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737728789,Glosa,Despacho,NaN,-4202,0,-798,-5000,0,-4202,0,100,0,STGO,STGO,STGO,Sin datos
3129,Devolucion,Casa Matriz,VENTA ONLINE,Marie Helene Ducheylard,10251278-2,nota de crédito electrónica,6827,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sandalia,22501603004005,Via Uno Sandalia 22501603 Blanco,35,NaN,-17639,-1,-3351,-20990,10405,-17639,10405,100,0,STGO,STGO,STGO,Sin datos
3130,Devolucion,Casa Matriz,VENTA ONLINE,Marie Helene Ducheylard,10251278-2,nota de crédito electrónica,6827,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737902477,Glosa,Despacho,NaN,-3353,0,-637,-3990,0,-3353,0,100,0,STGO,STGO,STGO,Sin datos

In [21]:
# Modify with the correct Margen and % Margen for each row
principal['Margen'] = principal['Precio Neto Unitario'] * principal['Cantidad'] - abs(principal['Costo Total Neto'])
principal['% Margen'] = principal['Margen'] / (principal['Precio Neto Unitario']* abs(principal['Cantidad'])) *100
principal['% Margen'] = principal['% Margen'].round(2).fillna(0) #We want to show the percentage with 2 decimals
principal.head()

,Tipo Movimiento,Sucursal,Vendedor,Cliente,Rut Cliente,Tipo de Documento,Numero Documento,Tracking Number,Fecha Documento,Fecha y Hora Venta,Lista de Precio,Tipo de Producto / Servicio,SKU,Producto / Servicio,Variante,Otros Atributos,Precio Neto Unitario,Cantidad,Subtotal Impuestos,Subtotal Bruto,Costo Neto Unitario,Margen,Costo Total Neto,% Margen,Detalle de Productos/Servicios Pack/Promo,Dirección Cliente,Comuna Cliente,Ciudad Cliente,Email Cliente
0,Venta,Casa Matriz,VENTA ONLINE,Catalina Cusó,20415182-2,boleta electrónica t,37678,6774be78b0bd82e806fb1398,01/01/2025,01/01/2025 01:03 AM,Lista de Precios Base,Sandalia,22533601009006,Via Uno Sandalia 22533601 Crema,36,NaN,21845,1,4150,25996,-15954,5891,-15954,26.97,0,Sin datos,Sin datos,Sin datos,cata0cuso@gmail.com
1,Venta,Casa Matriz,VENTA ONLINE,Catalina Cusó,20415182-2,boleta electrónica t,37678,6774be78b0bd82e806fb1398,01/01/2025,01/01/2025 01:03 AM,Lista de Precios Base,Sin Tipo,1735704183,Glosa,Despacho,NaN,5876,1,1117,6993,0,5876,0,100.00,0,Sin datos,Sin datos,Sin datos,cata0cuso@gmail.com
2,Venta,Casa Matriz,VENTA ONLINE,Antonia Muñoz Reymond,16365935-2,boleta electrónica t,37679,6774cc4ab0bd82e806fb1601,01/01/2025,01/01/2025 02:02 AM,Lista de Precios Base,Sandalia,22501603015007,Via Uno Sandalia 22501603 Negro,37,NaN,17639,1,3351,20990,-10405,7234,-10405,41.01,0,Sin datos,Sin datos,Sin datos,antoniamr@gmail.com
3,Venta,Casa Matriz,VENTA ONLINE,Johanna Quitral Henriquez,13912101-5,boleta electrónica t,37680,6774e19a6a3f329377f8eaf5,01/01/2025,01/01/2025 03:32 AM,Lista de Precios Base,Sandalia,22541607015009,Via Uno Sandalia 22541607 Negro,39,NaN,15123,1,2873,17996,-8400,6723,-8400,44.46,0,Sin datos,Sin datos,Sin datos,johannaquitralh@gmail.com
4,Venta,Casa Matriz,VENTA ONLINE,Johanna Quitral Henriquez,13912101-5,boleta electrónica t,37680,6774e19a6a3f329377f8eaf5,01/01/2025,01/01/2025 03:32 AM,Lista de Precios Base,Sandalia,22541603015006,Via Uno Sandalia 22541603 Negro,36,NaN,18903,1,3592,22495,-11075,7828,-11075,41.41,0,Sin datos,Sin datos,Sin datos,johannaquitralh@gmail.com

We need to set the Marketplace on principal using the dictionary obtained earlier.

In [22]:
#set Marketplace for principal
principal['Marketplace'] = principal['Numero Documento'].map(marketplace_dict).fillna("Sin datos")

# All rows on Marketplace with lowercase
principal['Marketplace'] = principal['Marketplace'].str.lower()

principal.tail()

,Tipo Movimiento,Sucursal,Vendedor,Cliente,Rut Cliente,Tipo de Documento,Numero Documento,Tracking Number,Fecha Documento,Fecha y Hora Venta,Lista de Precio,Tipo de Producto / Servicio,SKU,Producto / Servicio,Variante,Otros Atributos,Precio Neto Unitario,Cantidad,Subtotal Impuestos,Subtotal Bruto,Costo Neto Unitario,Margen,Costo Total Neto,% Margen,Detalle de Productos/Servicios Pack/Promo,Dirección Cliente,Comuna Cliente,Ciudad Cliente,Email Cliente,Marketplace
3126,Devolucion,Casa Matriz,VENTA ONLINE,Cecilia Riquelme,9748952-1,nota de crédito electrónica,6825,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737160877,Glosa,Despacho,NaN,-5042,0,-958,-6000,0,0,0,0.00,0,STGO,STGO,STGO,Sin datos,ripley
3127,Devolucion,Casa Matriz,VENTA ONLINE,Pamela Del Carmen Pena Munoz,15393062-7,nota de crédito electrónica,6826,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Bota,22513301003009,Via Uno Bota 22513301 Beige,39,NaN,-30244,-1,-5747,-35990,20372,9872,20372,-32.64,0,STGO,STGO,STGO,Sin datos,ripley
3128,Devolucion,Casa Matriz,VENTA ONLINE,Pamela Del Carmen Pena Munoz,15393062-7,nota de crédito electrónica,6826,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737728789,Glosa,Despacho,NaN,-4202,0,-798,-5000,0,0,0,0.00,0,STGO,STGO,STGO,Sin datos,ripley
3129,Devolucion,Casa Matriz,VENTA ONLINE,Marie Helene Ducheylard,10251278-2,nota de crédito electrónica,6827,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sandalia,22501603004005,Via Uno Sandalia 22501603 Blanco,35,NaN,-17639,-1,-3351,-20990,10405,7234,10405,-41.01,0,STGO,STGO,STGO,Sin datos,ripley
3130,Devolucion,Casa Matriz,VENTA ONLINE,Marie Helene Ducheylard,10251278-2,nota de crédito electrónica,6827,Sin datos,31/01/2025,30/01/2025 09:00 PM,Lista de Precios Base,Sin Tipo,1737902477,Glosa,Despacho,NaN,-3353,0,-637,-3990,0,0,0,0.00,0,STGO,STGO,STGO,Sin datos,ripley

Now we need to create a column named Producto. This can be obtained by truncating the SKU to the first 8 digits.

In [23]:
#Create column Producto 
principal['Producto']=principal['SKU'].str[:8]
principal.head()

,Tipo Movimiento,Sucursal,Vendedor,Cliente,Rut Cliente,Tipo de Documento,Numero Documento,Tracking Number,Fecha Documento,Fecha y Hora Venta,Lista de Precio,Tipo de Producto / Servicio,SKU,Producto / Servicio,Variante,Otros Atributos,Precio Neto Unitario,Cantidad,Subtotal Impuestos,Subtotal Bruto,Costo Neto Unitario,Margen,Costo Total Neto,% Margen,Detalle de Productos/Servicios Pack/Promo,Dirección Cliente,Comuna Cliente,Ciudad Cliente,Email Cliente,Marketplace,Producto
0,Venta,Casa Matriz,VENTA ONLINE,Catalina Cusó,20415182-2,boleta electrónica t,37678,6774be78b0bd82e806fb1398,01/01/2025,01/01/2025 01:03 AM,Lista de Precios Base,Sandalia,22533601009006,Via Uno Sandalia 22533601 Crema,36,NaN,21845,1,4150,25996,-15954,5891,-15954,26.97,0,Sin datos,Sin datos,Sin datos,cata0cuso@gmail.com,vtex,22533601
1,Venta,Casa Matriz,VENTA ONLINE,Catalina Cusó,20415182-2,boleta electrónica t,37678,6774be78b0bd82e806fb1398,01/01/2025,01/01/2025 01:03 AM,Lista de Precios Base,Sin Tipo,1735704183,Glosa,Despacho,NaN,5876,1,1117,6993,0,5876,0,100.00,0,Sin datos,Sin datos,Sin datos,cata0cuso@gmail.com,vtex,17357041
2,Venta,Casa Matriz,VENTA ONLINE,Antonia Muñoz Reymond,16365935-2,boleta electrónica t,37679,6774cc4ab0bd82e806fb1601,01/01/2025,01/01/2025 02:02 AM,Lista de Precios Base,Sandalia,22501603015007,Via Uno Sandalia 22501603 Negro,37,NaN,17639,1,3351,20990,-10405,7234,-10405,41.01,0,Sin datos,Sin datos,Sin datos,antoniamr@gmail.com,paris,22501603
3,Venta,Casa Matriz,VENTA ONLINE,Johanna Quitral Henriquez,13912101-5,boleta electrónica t,37680,6774e19a6a3f329377f8eaf5,01/01/2025,01/01/2025 03:32 AM,Lista de Precios Base,Sandalia,22541607015009,Via Uno Sandalia 22541607 Negro,39,NaN,15123,1,2873,17996,-8400,6723,-8400,44.46,0,Sin datos,Sin datos,Sin datos,johannaquitralh@gmail.com,vtex,22541607
4,Venta,Casa Matriz,VENTA ONLINE,Johanna Quitral Henriquez,13912101-5,boleta electrónica t,37680,6774e19a6a3f329377f8eaf5,01/01/2025,01/01/2025 03:32 AM,Lista de Precios Base,Sandalia,22541603015006,Via Uno Sandalia 22541603 Negro,36,NaN,18903,1,3592,22495,-11075,7828,-11075,41.41,0,Sin datos,Sin datos,Sin datos,johannaquitralh@gmail.com,vtex,22541603

#### Checking if len of dataframe is the same get before

In [24]:
# Verify the len of the final dataframe
num_principal2 = len(principal)

#Compare the len of the dataframe for principal considering now needs to be 1 row less because we eliminate the last row
if num_principal -1 == num_principal2:
    print(f"The dataframes have the same length, {num_principal -1 } and {num_principal2}")
else:
    print(f"The dataframes have different lengths, {num_principal - 1} and {num_principal2}")

The dataframes have the same length, 3131 and 3131

# Group by Marketplace table

In [25]:
# Filter by rows that are not Despacho
principal_group = principal[principal['Variante'] != 'Despacho']

# Create a new column with the Precio Neto per row
principal_group['Precio Neto'] = principal_group['Subtotal Bruto'] - principal_group['Subtotal Impuestos']

# Group by Marketplace, Sucursal, Producto
principal_Marketplace = principal_group.groupby(['Marketplace']).agg(
    {'Cantidad': 'sum', 'Precio Neto': 'sum','Costo Total Neto': 'sum'}).reset_index()

# Calculate the margin
principal_Marketplace['Margen'] = principal_Marketplace['Precio Neto'] + principal_Marketplace['Costo Total Neto'] #It is positive because the cost is already negative
principal_Marketplace['% Margen'] = (principal_Marketplace['Margen'] / abs(principal_Marketplace['Precio Neto'])) * 100
principal_Marketplace['% Margen'] = principal_Marketplace['% Margen'].round(2).fillna(0)

# Order by % Margen
principal_Marketplace = principal_Marketplace.sort_values(by='% Margen', ascending=False)
principal_Marketplace

  Marketplace  Cantidad  Precio Neto  Costo Total Neto   Margen  % Margen
3   sin datos         1      1610000                 0  1610000    100.00
4         vpm       -35      -210721            378307   167586     79.53
0        fcom       505     10384843          -5373967  5010876     48.25
1       paris       111      2196473          -1156580  1039893     47.34
2      ripley        46      1117260           -598849   518411     46.40
5        vtex       930     15663390          -9922397  5740993     36.65

# Group by Tipo de Producto / Servicio table

In [26]:
# Group by Tipo de Producto / Servicio 

principal_Producto = principal_group.groupby(['Tipo de Producto / Servicio']).agg(
    {'Cantidad': 'sum', 'Precio Neto': 'sum','Costo Total Neto': 'sum'}).reset_index() 

# Calculate the margin
principal_Producto['Margen'] = principal_Producto['Precio Neto'] + principal_Producto['Costo Total Neto'] #It is positive because the cost is already negative
principal_Producto['% Margen'] = (principal_Producto['Margen'] / abs(principal_Producto['Precio Neto'])) * 100
principal_Producto['% Margen'] = principal_Producto['% Margen'].round(2).fillna(0)

# Order by % Margen
principal_Producto = principal_Producto.sort_values(by='% Margen', ascending=False)
principal_Producto

,Tipo de Producto / Servicio,Cantidad,Precio Neto,Costo Total Neto,Margen,% Margen
4,Sin Tipo,8,1715264,0,1715264,100.00
3,Sandalia,1285,23343698,-13092358,10251340,43.91
6,Zapato,103,1959537,-1116417,843120,43.03
1,Botin,58,1380915,-887993,492922,35.70
5,Zapatilla,76,1584939,-1041109,543830,34.31
0,Bota,27,770174,-528459,241715,31.38
2,Playera,1,6718,-7150,-432,-6.43

# Filter Product with % Margen <=20%

In [27]:
Low_Margen_Marketplace = principal_Marketplace[principal_Marketplace['% Margen'] <= 20]
Low_Margen_Producto = principal_Producto[principal_Producto['% Margen'] <= 20]

display(Low_Margen_Marketplace)
display(Low_Margen_Producto)

Empty DataFrame
Columns: [Marketplace, Cantidad, Precio Neto, Costo Total Neto, Margen, % Margen]
Index: []

,Tipo de Producto / Servicio,Cantidad,Precio Neto,Costo Total Neto,Margen,% Margen
2,Playera,1,6718,-7150,-432,-6.43

# Export to Excel

In [28]:
def set_column_formatting(writer, df, sheet_name):
    workbook  = writer.book
    worksheet = writer.sheets[sheet_name]
    header_format = workbook.add_format({'bold': True, 'bg_color': '#F9DA04', 'border': 1})
    # Recorre cada columna para establecer ancho y formatear el encabezado
    for i, col in enumerate(df.columns):
        max_len = max(df[col].fillna("").astype(str).map(len).max(), len(col)) + 2
        worksheet.set_column(i, i, max_len)
        worksheet.write(0, i, col, header_format)

# Export principal.xlsx con cada DataFrame en una hoja separada
with pd.ExcelWriter("principal.xlsx", engine="xlsxwriter") as writer:
    # Hoja para el DataFrame principal
    principal.to_excel(writer, sheet_name="Principal", index=False)
    set_column_formatting(writer, principal, "Principal")
    
    # Hoja para principal_Marketplace
    principal_Marketplace.to_excel(writer, sheet_name="Principal Marketplace", index=False)
    set_column_formatting(writer, principal_Marketplace, "Principal Marketplace")
    
    # Hoja para principal_Producto
    principal_Producto.to_excel(writer, sheet_name="Principal Producto", index=False)
    set_column_formatting(writer, principal_Producto, "Principal Producto")
    
    # Hoja para Low_Margen_Marketplace
    Low_Margen_Marketplace.to_excel(writer, sheet_name="Low Margen Marketplace", index=False)
    set_column_formatting(writer, Low_Margen_Marketplace, "Low Margen Marketplace")
    
    # Hoja para Low_Margen_Producto
    Low_Margen_Producto.to_excel(writer, sheet_name="Low Margen Producto", index=False)
    set_column_formatting(writer, Low_Margen_Producto, "Low Margen Producto")

# Export final_table.xlsx en una única hoja ("Final Table")
with pd.ExcelWriter("final_table.xlsx", engine="xlsxwriter") as writer:
    final_table.to_excel(writer, sheet_name="Final Table", index=False)
    set_column_formatting(writer, final_table, "Final Table")